/*
*  Copyright 2024 MASES s.r.l.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*  http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*
*  Refer to LICENSE for more information.
*/

/*
*  This file is generated by MASES.JNetReflector (ver. 2.5.8.0)
*  using java.* as reference
*/

using MASES.JCOBridge.C2JBridge;

namespace Javax.Swing.Event
{
    #region ICaretListener
    /// <summary>
    /// .NET interface for org.mases.jnet.generated.javax.swing.event.CaretListener implementing <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/event/CaretListener.html"/>
    /// </summary>
    public partial interface ICaretListener
    {
        #region Instance methods
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/event/CaretListener.html#caretUpdate(javax.swing.event.CaretEvent)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Javax.Swing.Event.CaretEvent"/></param>
        void CaretUpdate(Javax.Swing.Event.CaretEvent arg0);

        #endregion

        #region Nested classes

        #endregion

        // TODO: complete the class
    }
    #endregion

    #region CaretListener
    public partial class CaretListener : Javax.Swing.Event.ICaretListener
    {
        #region Constructors

        #endregion

        #region Class/Interface conversion operators

        #endregion

        #region Fields

        #endregion

        #region Static methods

        #endregion

        #region Instance methods
        /// <summary>
        /// Handlers initializer for <see cref="CaretListener"/>
        /// </summary>
        protected virtual void InitializeHandlers()
        {
            AddEventHandler("caretUpdate", new global::System.EventHandler<CLRListenerEventArgs<CLREventData<Javax.Swing.Event.CaretEvent>>>(CaretUpdateEventHandler));

        }

        /// <summary>
        /// Handler for <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/event/CaretListener.html#caretUpdate(javax.swing.event.CaretEvent)"/>
        /// </summary>
        /// <remarks>If <see cref="OnCaretUpdate"/> has a value it takes precedence over corresponding class method</remarks>
        public global::System.Action<Javax.Swing.Event.CaretEvent> OnCaretUpdate { get; set; } = null;

        void CaretUpdateEventHandler(object sender, CLRListenerEventArgs<CLREventData<Javax.Swing.Event.CaretEvent>> data)
        {
            var methodToExecute = (OnCaretUpdate != null) ? OnCaretUpdate : CaretUpdate;
            methodToExecute.Invoke(data.EventData.TypedEventData);
        }

        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/event/CaretListener.html#caretUpdate(javax.swing.event.CaretEvent)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Javax.Swing.Event.CaretEvent"/></param>
        public virtual void CaretUpdate(Javax.Swing.Event.CaretEvent arg0)
        {
            
        }

        #endregion

        #region Nested classes

        #endregion

        // TODO: complete the class
    }
    #endregion

    #region CaretListenerDirect
    public partial class CaretListenerDirect : Javax.Swing.Event.ICaretListener
    {
        #region Constructors

        #endregion

        #region Class/Interface conversion operators

        #endregion

        #region Fields

        #endregion

        #region Static methods

        #endregion

        #region Instance methods
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/event/CaretListener.html#caretUpdate(javax.swing.event.CaretEvent)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Javax.Swing.Event.CaretEvent"/></param>
        public override void CaretUpdate(Javax.Swing.Event.CaretEvent arg0)
        {
            IExecuteWithSignature("caretUpdate", "(Ljavax/swing/event/CaretEvent;)V", arg0);
        }

        #endregion

        #region Nested classes

        #endregion

        // TODO: complete the class
    }
    #endregion
}