/*
*  Copyright 2024 MASES s.r.l.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*  http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*
*  Refer to LICENSE for more information.
*/

/*
*  This file is generated by MASES.JNetReflector (ver. 2.5.8.0)
*  using java.* as reference
*/

using MASES.JCOBridge.C2JBridge;

namespace Javax.Swing.Text
{
    #region AbstractDocument
    public partial class AbstractDocument
    {
        #region Constructors

        #endregion

        #region Class/Interface conversion operators
        /// <summary>
        /// Converter from <see cref="Javax.Swing.Text.AbstractDocument"/> to <see cref="Javax.Swing.Text.Document"/>
        /// </summary>
        public static implicit operator Javax.Swing.Text.Document(Javax.Swing.Text.AbstractDocument t) => t.Cast<Javax.Swing.Text.Document>();
        /// <summary>
        /// Converter from <see cref="Javax.Swing.Text.AbstractDocument"/> to <see cref="Java.Io.Serializable"/>
        /// </summary>
        public static implicit operator Java.Io.Serializable(Javax.Swing.Text.AbstractDocument t) => t.Cast<Java.Io.Serializable>();

        #endregion

        #region Fields
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#BidiElementName"/>
        /// </summary>
        public static Java.Lang.String BidiElementName { get { if (!_BidiElementNameReady) { _BidiElementNameContent = SGetField<Java.Lang.String>(LocalBridgeClazz, "BidiElementName"); _BidiElementNameReady = true; } return _BidiElementNameContent; } }
        private static Java.Lang.String _BidiElementNameContent = default;
        private static bool _BidiElementNameReady = false; // this is used because in case of generics 
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#ContentElementName"/>
        /// </summary>
        public static Java.Lang.String ContentElementName { get { if (!_ContentElementNameReady) { _ContentElementNameContent = SGetField<Java.Lang.String>(LocalBridgeClazz, "ContentElementName"); _ContentElementNameReady = true; } return _ContentElementNameContent; } }
        private static Java.Lang.String _ContentElementNameContent = default;
        private static bool _ContentElementNameReady = false; // this is used because in case of generics 
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#ElementNameAttribute"/>
        /// </summary>
        public static Java.Lang.String ElementNameAttribute { get { if (!_ElementNameAttributeReady) { _ElementNameAttributeContent = SGetField<Java.Lang.String>(LocalBridgeClazz, "ElementNameAttribute"); _ElementNameAttributeReady = true; } return _ElementNameAttributeContent; } }
        private static Java.Lang.String _ElementNameAttributeContent = default;
        private static bool _ElementNameAttributeReady = false; // this is used because in case of generics 
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#ParagraphElementName"/>
        /// </summary>
        public static Java.Lang.String ParagraphElementName { get { if (!_ParagraphElementNameReady) { _ParagraphElementNameContent = SGetField<Java.Lang.String>(LocalBridgeClazz, "ParagraphElementName"); _ParagraphElementNameReady = true; } return _ParagraphElementNameContent; } }
        private static Java.Lang.String _ParagraphElementNameContent = default;
        private static bool _ParagraphElementNameReady = false; // this is used because in case of generics 
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#SectionElementName"/>
        /// </summary>
        public static Java.Lang.String SectionElementName { get { if (!_SectionElementNameReady) { _SectionElementNameContent = SGetField<Java.Lang.String>(LocalBridgeClazz, "SectionElementName"); _SectionElementNameReady = true; } return _SectionElementNameContent; } }
        private static Java.Lang.String _SectionElementNameContent = default;
        private static bool _SectionElementNameReady = false; // this is used because in case of generics 

        #endregion

        #region Static methods

        #endregion

        #region Instance methods
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#getAsynchronousLoadPriority()"/> <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#setAsynchronousLoadPriority(int)"/>
        /// </summary>
        public int AsynchronousLoadPriority
        {
            get { return IExecuteWithSignature<int>("getAsynchronousLoadPriority", "()I"); } set { IExecuteWithSignature("setAsynchronousLoadPriority", "(I)V", value); }
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#getDefaultRootElement()"/> 
        /// </summary>
        public Javax.Swing.Text.Element DefaultRootElement
        {
            get { return IExecuteWithSignature<Javax.Swing.Text.Element>("getDefaultRootElement", "()Ljavax/swing/text/Element;"); }
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#getDocumentFilter()"/> <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#setDocumentFilter(javax.swing.text.DocumentFilter)"/>
        /// </summary>
        public Javax.Swing.Text.DocumentFilter DocumentFilter
        {
            get { return IExecuteWithSignature<Javax.Swing.Text.DocumentFilter>("getDocumentFilter", "()Ljavax/swing/text/DocumentFilter;"); } set { IExecuteWithSignature("setDocumentFilter", "(Ljavax/swing/text/DocumentFilter;)V", value); }
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#getDocumentListeners()"/> 
        /// </summary>
        public Javax.Swing.Event.DocumentListener[] DocumentListeners
        {
            get { return IExecuteWithSignatureArray<Javax.Swing.Event.DocumentListener>("getDocumentListeners", "()[Ljavax/swing/event/DocumentListener;"); }
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#getDocumentProperties()"/> <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#setDocumentProperties(java.util.Dictionary)"/>
        /// </summary>
        public Java.Util.Dictionary<object, object> DocumentProperties
        {
            get { return IExecuteWithSignature<Java.Util.Dictionary<object, object>>("getDocumentProperties", "()Ljava/util/Dictionary;"); } set { IExecuteWithSignature("setDocumentProperties", "(Ljava/util/Dictionary;)V", value); }
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#getEndPosition()"/> 
        /// </summary>
        public Javax.Swing.Text.Position EndPosition
        {
            get { return IExecuteWithSignature<Javax.Swing.Text.Position>("getEndPosition", "()Ljavax/swing/text/Position;"); }
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#getBidiRootElement()"/> 
        /// </summary>
        public Javax.Swing.Text.Element GetBidiRootElement
        {
            get { return IExecuteWithSignature<Javax.Swing.Text.Element>("getBidiRootElement", "()Ljavax/swing/text/Element;"); }
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#getLength()"/> 
        /// </summary>
        public int Length
        {
            get { return IExecuteWithSignature<int>("getLength", "()I"); }
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#getRootElements()"/> 
        /// </summary>
        public Javax.Swing.Text.Element[] RootElements
        {
            get { return IExecuteWithSignatureArray<Javax.Swing.Text.Element>("getRootElements", "()[Ljavax/swing/text/Element;"); }
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#getStartPosition()"/> 
        /// </summary>
        public Javax.Swing.Text.Position StartPosition
        {
            get { return IExecuteWithSignature<Javax.Swing.Text.Position>("getStartPosition", "()Ljavax/swing/text/Position;"); }
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#getUndoableEditListeners()"/> 
        /// </summary>
        public Javax.Swing.Event.UndoableEditListener[] UndoableEditListeners
        {
            get { return IExecuteWithSignatureArray<Javax.Swing.Event.UndoableEditListener>("getUndoableEditListeners", "()[Ljavax/swing/event/UndoableEditListener;"); }
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#getListeners(java.lang.Class)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Java.Lang.Class"/></param>
        /// <typeparam name="T"><see cref="Java.Util.IEventListener"/></typeparam>
        /// <returns><typeparamref name="T"/></returns>
        public T[] GetListeners<T>(Java.Lang.Class arg0) where T : Java.Util.IEventListener, new()
        {
            return IExecuteArray<T>("getListeners", arg0);
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#getParagraphElement(int)"/>
        /// </summary>
        /// <param name="arg0"><see cref="int"/></param>
        /// <returns><see cref="Javax.Swing.Text.Element"/></returns>
        public Javax.Swing.Text.Element GetParagraphElement(int arg0)
        {
            return IExecuteWithSignature<Javax.Swing.Text.Element>("getParagraphElement", "(I)Ljavax/swing/text/Element;", arg0);
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#getProperty(java.lang.Object)"/>
        /// </summary>
        /// <param name="arg0"><see cref="object"/></param>
        /// <returns><see cref="object"/></returns>
        public object GetProperty(object arg0)
        {
            return IExecuteWithSignature("getProperty", "(Ljava/lang/Object;)Ljava/lang/Object;", arg0);
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#readLock()"/>
        /// </summary>
        public void ReadLock()
        {
            IExecuteWithSignature("readLock", "()V");
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#readUnlock()"/>
        /// </summary>
        public void ReadUnlock()
        {
            IExecuteWithSignature("readUnlock", "()V");
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#putProperty(java.lang.Object,java.lang.Object)"/>
        /// </summary>
        /// <param name="arg0"><see cref="object"/></param>
        /// <param name="arg1"><see cref="object"/></param>
        public void PutProperty(object arg0, object arg1)
        {
            IExecute("putProperty", arg0, arg1);
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#getText(int,int)"/>
        /// </summary>
        /// <param name="arg0"><see cref="int"/></param>
        /// <param name="arg1"><see cref="int"/></param>
        /// <returns><see cref="Java.Lang.String"/></returns>
        /// <exception cref="Javax.Swing.Text.BadLocationException"/>
        public Java.Lang.String GetText(int arg0, int arg1)
        {
            return IExecute<Java.Lang.String>("getText", arg0, arg1);
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#createPosition(int)"/>
        /// </summary>
        /// <param name="arg0"><see cref="int"/></param>
        /// <returns><see cref="Javax.Swing.Text.Position"/></returns>
        /// <exception cref="Javax.Swing.Text.BadLocationException"/>
        public Javax.Swing.Text.Position CreatePosition(int arg0)
        {
            return IExecuteWithSignature<Javax.Swing.Text.Position>("createPosition", "(I)Ljavax/swing/text/Position;", arg0);
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#addDocumentListener(javax.swing.event.DocumentListener)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Javax.Swing.Event.DocumentListener"/></param>
        public void AddDocumentListener(Javax.Swing.Event.DocumentListener arg0)
        {
            IExecuteWithSignature("addDocumentListener", "(Ljavax/swing/event/DocumentListener;)V", arg0);
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#addUndoableEditListener(javax.swing.event.UndoableEditListener)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Javax.Swing.Event.UndoableEditListener"/></param>
        public void AddUndoableEditListener(Javax.Swing.Event.UndoableEditListener arg0)
        {
            IExecuteWithSignature("addUndoableEditListener", "(Ljavax/swing/event/UndoableEditListener;)V", arg0);
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#dump(java.io.PrintStream)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Java.Io.PrintStream"/></param>
        public void Dump(Java.Io.PrintStream arg0)
        {
            IExecuteWithSignature("dump", "(Ljava/io/PrintStream;)V", arg0);
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#getText(int,int,javax.swing.text.Segment)"/>
        /// </summary>
        /// <param name="arg0"><see cref="int"/></param>
        /// <param name="arg1"><see cref="int"/></param>
        /// <param name="arg2"><see cref="Javax.Swing.Text.Segment"/></param>
        /// <exception cref="Javax.Swing.Text.BadLocationException"/>
        public void GetText(int arg0, int arg1, Javax.Swing.Text.Segment arg2)
        {
            IExecute("getText", arg0, arg1, arg2);
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#insertString(int,java.lang.String,javax.swing.text.AttributeSet)"/>
        /// </summary>
        /// <param name="arg0"><see cref="int"/></param>
        /// <param name="arg1"><see cref="Java.Lang.String"/></param>
        /// <param name="arg2"><see cref="Javax.Swing.Text.AttributeSet"/></param>
        /// <exception cref="Javax.Swing.Text.BadLocationException"/>
        public void InsertString(int arg0, Java.Lang.String arg1, Javax.Swing.Text.AttributeSet arg2)
        {
            IExecute("insertString", arg0, arg1, arg2);
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#remove(int,int)"/>
        /// </summary>
        /// <param name="arg0"><see cref="int"/></param>
        /// <param name="arg1"><see cref="int"/></param>
        /// <exception cref="Javax.Swing.Text.BadLocationException"/>
        public void Remove(int arg0, int arg1)
        {
            IExecute("remove", arg0, arg1);
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#removeDocumentListener(javax.swing.event.DocumentListener)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Javax.Swing.Event.DocumentListener"/></param>
        public void RemoveDocumentListener(Javax.Swing.Event.DocumentListener arg0)
        {
            IExecuteWithSignature("removeDocumentListener", "(Ljavax/swing/event/DocumentListener;)V", arg0);
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#removeUndoableEditListener(javax.swing.event.UndoableEditListener)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Javax.Swing.Event.UndoableEditListener"/></param>
        public void RemoveUndoableEditListener(Javax.Swing.Event.UndoableEditListener arg0)
        {
            IExecuteWithSignature("removeUndoableEditListener", "(Ljavax/swing/event/UndoableEditListener;)V", arg0);
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#render(java.lang.Runnable)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Java.Lang.Runnable"/></param>
        public void Render(Java.Lang.Runnable arg0)
        {
            IExecuteWithSignature("render", "(Ljava/lang/Runnable;)V", arg0);
        }
        /// <summary>
        /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.html#replace(int,int,java.lang.String,javax.swing.text.AttributeSet)"/>
        /// </summary>
        /// <param name="arg0"><see cref="int"/></param>
        /// <param name="arg1"><see cref="int"/></param>
        /// <param name="arg2"><see cref="Java.Lang.String"/></param>
        /// <param name="arg3"><see cref="Javax.Swing.Text.AttributeSet"/></param>
        /// <exception cref="Javax.Swing.Text.BadLocationException"/>
        public void Replace(int arg0, int arg1, Java.Lang.String arg2, Javax.Swing.Text.AttributeSet arg3)
        {
            IExecute("replace", arg0, arg1, arg2, arg3);
        }

        #endregion

        #region Nested classes
        #region AbstractElement
        public partial class AbstractElement
        {
            #region Constructors
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#%3Cinit%3E(javax.swing.text.AbstractDocument,javax.swing.text.Element,javax.swing.text.AttributeSet)"/>
            /// </summary>
            /// <param name="arg0"><see cref="Javax.Swing.Text.AbstractDocument"/></param>
            /// <param name="arg1"><see cref="Javax.Swing.Text.Element"/></param>
            /// <param name="arg2"><see cref="Javax.Swing.Text.AttributeSet"/></param>
            public AbstractElement(Javax.Swing.Text.AbstractDocument arg0, Javax.Swing.Text.Element arg1, Javax.Swing.Text.AttributeSet arg2)
                : base(arg0, arg1, arg2)
            {
            }

            #endregion

            #region Class/Interface conversion operators
            /// <summary>
            /// Converter from <see cref="Javax.Swing.Text.AbstractDocument.AbstractElement"/> to <see cref="Javax.Swing.Text.Element"/>
            /// </summary>
            public static implicit operator Javax.Swing.Text.Element(Javax.Swing.Text.AbstractDocument.AbstractElement t) => t.Cast<Javax.Swing.Text.Element>();
            /// <summary>
            /// Converter from <see cref="Javax.Swing.Text.AbstractDocument.AbstractElement"/> to <see cref="Javax.Swing.Text.MutableAttributeSet"/>
            /// </summary>
            public static implicit operator Javax.Swing.Text.MutableAttributeSet(Javax.Swing.Text.AbstractDocument.AbstractElement t) => t.Cast<Javax.Swing.Text.MutableAttributeSet>();
            /// <summary>
            /// Converter from <see cref="Javax.Swing.Text.AbstractDocument.AbstractElement"/> to <see cref="Java.Io.Serializable"/>
            /// </summary>
            public static implicit operator Java.Io.Serializable(Javax.Swing.Text.AbstractDocument.AbstractElement t) => t.Cast<Java.Io.Serializable>();
            /// <summary>
            /// Converter from <see cref="Javax.Swing.Text.AbstractDocument.AbstractElement"/> to <see cref="Javax.Swing.Tree.TreeNode"/>
            /// </summary>
            public static implicit operator Javax.Swing.Tree.TreeNode(Javax.Swing.Text.AbstractDocument.AbstractElement t) => t.Cast<Javax.Swing.Tree.TreeNode>();

            #endregion

            #region Fields

            #endregion

            #region Static methods

            #endregion

            #region Instance methods
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#getAllowsChildren()"/> 
            /// </summary>
            public bool AllowsChildren
            {
                get { return IExecuteWithSignature<bool>("getAllowsChildren", "()Z"); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#getAttributeCount()"/> 
            /// </summary>
            public int AttributeCount
            {
                get { return IExecuteWithSignature<int>("getAttributeCount", "()I"); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#getAttributeNames()"/> 
            /// </summary>
            public Java.Util.Enumeration<object> AttributeNames
            {
                get { return IExecuteWithSignature<Java.Util.Enumeration<object>>("getAttributeNames", "()Ljava/util/Enumeration;"); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#getAttributes()"/> 
            /// </summary>
            public Javax.Swing.Text.AttributeSet Attributes
            {
                get { return IExecuteWithSignature<Javax.Swing.Text.AttributeSet>("getAttributes", "()Ljavax/swing/text/AttributeSet;"); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#getChildCount()"/> 
            /// </summary>
            public int ChildCount
            {
                get { return IExecuteWithSignature<int>("getChildCount", "()I"); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#getDocument()"/> 
            /// </summary>
            public Javax.Swing.Text.Document Document
            {
                get { return IExecuteWithSignature<Javax.Swing.Text.Document>("getDocument", "()Ljavax/swing/text/Document;"); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#getElementCount()"/> 
            /// </summary>
            public int ElementCount
            {
                get { return IExecuteWithSignature<int>("getElementCount", "()I"); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#getEndOffset()"/> 
            /// </summary>
            public int EndOffset
            {
                get { return IExecuteWithSignature<int>("getEndOffset", "()I"); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#getName()"/> 
            /// </summary>
            public Java.Lang.String Name
            {
                get { return IExecuteWithSignature<Java.Lang.String>("getName", "()Ljava/lang/String;"); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#getParent()"/> 
            /// </summary>
            public Javax.Swing.Tree.TreeNode Parent
            {
                get { return IExecuteWithSignature<Javax.Swing.Tree.TreeNode>("getParent", "()Ljavax/swing/tree/TreeNode;"); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#getParentElement()"/> 
            /// </summary>
            public Javax.Swing.Text.Element ParentElement
            {
                get { return IExecuteWithSignature<Javax.Swing.Text.Element>("getParentElement", "()Ljavax/swing/text/Element;"); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#getResolveParent()"/> <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#setResolveParent(javax.swing.text.AttributeSet)"/>
            /// </summary>
            public Javax.Swing.Text.AttributeSet ResolveParent
            {
                get { return IExecuteWithSignature<Javax.Swing.Text.AttributeSet>("getResolveParent", "()Ljavax/swing/text/AttributeSet;"); } set { IExecuteWithSignature("setResolveParent", "(Ljavax/swing/text/AttributeSet;)V", value); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#getStartOffset()"/> 
            /// </summary>
            public int StartOffset
            {
                get { return IExecuteWithSignature<int>("getStartOffset", "()I"); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#isLeaf()"/>
            /// </summary>
            /// <returns><see cref="bool"/></returns>
            public bool IsLeaf()
            {
                return IExecuteWithSignature<bool>("isLeaf", "()Z");
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#getElementIndex(int)"/>
            /// </summary>
            /// <param name="arg0"><see cref="int"/></param>
            /// <returns><see cref="int"/></returns>
            public int GetElementIndex(int arg0)
            {
                return IExecuteWithSignature<int>("getElementIndex", "(I)I", arg0);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#children()"/>
            /// </summary>
            /// <returns><see cref="Java.Util.Enumeration"/></returns>
            public Java.Util.Enumeration<Javax.Swing.Tree.TreeNode> Children()
            {
                return IExecuteWithSignature<Java.Util.Enumeration<Javax.Swing.Tree.TreeNode>>("children", "()Ljava/util/Enumeration;");
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#getElement(int)"/>
            /// </summary>
            /// <param name="arg0"><see cref="int"/></param>
            /// <returns><see cref="Javax.Swing.Text.Element"/></returns>
            public Javax.Swing.Text.Element GetElement(int arg0)
            {
                return IExecuteWithSignature<Javax.Swing.Text.Element>("getElement", "(I)Ljavax/swing/text/Element;", arg0);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#containsAttribute(java.lang.Object,java.lang.Object)"/>
            /// </summary>
            /// <param name="arg0"><see cref="object"/></param>
            /// <param name="arg1"><see cref="object"/></param>
            /// <returns><see cref="bool"/></returns>
            public bool ContainsAttribute(object arg0, object arg1)
            {
                return IExecute<bool>("containsAttribute", arg0, arg1);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#containsAttributes(javax.swing.text.AttributeSet)"/>
            /// </summary>
            /// <param name="arg0"><see cref="Javax.Swing.Text.AttributeSet"/></param>
            /// <returns><see cref="bool"/></returns>
            public bool ContainsAttributes(Javax.Swing.Text.AttributeSet arg0)
            {
                return IExecuteWithSignature<bool>("containsAttributes", "(Ljavax/swing/text/AttributeSet;)Z", arg0);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#isDefined(java.lang.Object)"/>
            /// </summary>
            /// <param name="arg0"><see cref="object"/></param>
            /// <returns><see cref="bool"/></returns>
            public bool IsDefined(object arg0)
            {
                return IExecuteWithSignature<bool>("isDefined", "(Ljava/lang/Object;)Z", arg0);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#isEqual(javax.swing.text.AttributeSet)"/>
            /// </summary>
            /// <param name="arg0"><see cref="Javax.Swing.Text.AttributeSet"/></param>
            /// <returns><see cref="bool"/></returns>
            public bool IsEqual(Javax.Swing.Text.AttributeSet arg0)
            {
                return IExecuteWithSignature<bool>("isEqual", "(Ljavax/swing/text/AttributeSet;)Z", arg0);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#getIndex(javax.swing.tree.TreeNode)"/>
            /// </summary>
            /// <param name="arg0"><see cref="Javax.Swing.Tree.TreeNode"/></param>
            /// <returns><see cref="int"/></returns>
            public int GetIndex(Javax.Swing.Tree.TreeNode arg0)
            {
                return IExecuteWithSignature<int>("getIndex", "(Ljavax/swing/tree/TreeNode;)I", arg0);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#getAttribute(java.lang.Object)"/>
            /// </summary>
            /// <param name="arg0"><see cref="object"/></param>
            /// <returns><see cref="object"/></returns>
            public object GetAttribute(object arg0)
            {
                return IExecuteWithSignature("getAttribute", "(Ljava/lang/Object;)Ljava/lang/Object;", arg0);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#copyAttributes()"/>
            /// </summary>
            /// <returns><see cref="Javax.Swing.Text.AttributeSet"/></returns>
            public Javax.Swing.Text.AttributeSet CopyAttributes()
            {
                return IExecuteWithSignature<Javax.Swing.Text.AttributeSet>("copyAttributes", "()Ljavax/swing/text/AttributeSet;");
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#getChildAt(int)"/>
            /// </summary>
            /// <param name="arg0"><see cref="int"/></param>
            /// <returns><see cref="Javax.Swing.Tree.TreeNode"/></returns>
            public Javax.Swing.Tree.TreeNode GetChildAt(int arg0)
            {
                return IExecuteWithSignature<Javax.Swing.Tree.TreeNode>("getChildAt", "(I)Ljavax/swing/tree/TreeNode;", arg0);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#addAttribute(java.lang.Object,java.lang.Object)"/>
            /// </summary>
            /// <param name="arg0"><see cref="object"/></param>
            /// <param name="arg1"><see cref="object"/></param>
            public void AddAttribute(object arg0, object arg1)
            {
                IExecute("addAttribute", arg0, arg1);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#addAttributes(javax.swing.text.AttributeSet)"/>
            /// </summary>
            /// <param name="arg0"><see cref="Javax.Swing.Text.AttributeSet"/></param>
            public void AddAttributes(Javax.Swing.Text.AttributeSet arg0)
            {
                IExecuteWithSignature("addAttributes", "(Ljavax/swing/text/AttributeSet;)V", arg0);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#dump(java.io.PrintStream,int)"/>
            /// </summary>
            /// <param name="arg0"><see cref="Java.Io.PrintStream"/></param>
            /// <param name="arg1"><see cref="int"/></param>
            public void Dump(Java.Io.PrintStream arg0, int arg1)
            {
                IExecute("dump", arg0, arg1);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#removeAttribute(java.lang.Object)"/>
            /// </summary>
            /// <param name="arg0"><see cref="object"/></param>
            public void RemoveAttribute(object arg0)
            {
                IExecuteWithSignature("removeAttribute", "(Ljava/lang/Object;)V", arg0);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#removeAttributes(java.util.Enumeration)"/>
            /// </summary>
            /// <param name="arg0"><see cref="Java.Util.Enumeration"/></param>
            public void RemoveAttributes(Java.Util.Enumeration<object> arg0)
            {
                IExecuteWithSignature("removeAttributes", "(Ljava/util/Enumeration;)V", arg0);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AbstractElement.html#removeAttributes(javax.swing.text.AttributeSet)"/>
            /// </summary>
            /// <param name="arg0"><see cref="Javax.Swing.Text.AttributeSet"/></param>
            public void RemoveAttributes(Javax.Swing.Text.AttributeSet arg0)
            {
                IExecuteWithSignature("removeAttributes", "(Ljavax/swing/text/AttributeSet;)V", arg0);
            }

            #endregion

            #region Nested classes

            #endregion

            // TODO: complete the class
        }
        #endregion

        #region AttributeContext
        public partial class AttributeContext
        {
            #region Constructors

            #endregion

            #region Class/Interface conversion operators

            #endregion

            #region Fields

            #endregion

            #region Static methods

            #endregion

            #region Instance methods
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AttributeContext.html#getEmptySet()"/> 
            /// </summary>
            public Javax.Swing.Text.AttributeSet EmptySet
            {
                get { return IExecuteWithSignature<Javax.Swing.Text.AttributeSet>("getEmptySet", "()Ljavax/swing/text/AttributeSet;"); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AttributeContext.html#addAttribute(javax.swing.text.AttributeSet,java.lang.Object,java.lang.Object)"/>
            /// </summary>
            /// <param name="arg0"><see cref="Javax.Swing.Text.AttributeSet"/></param>
            /// <param name="arg1"><see cref="object"/></param>
            /// <param name="arg2"><see cref="object"/></param>
            /// <returns><see cref="Javax.Swing.Text.AttributeSet"/></returns>
            public Javax.Swing.Text.AttributeSet AddAttribute(Javax.Swing.Text.AttributeSet arg0, object arg1, object arg2)
            {
                return IExecute<Javax.Swing.Text.AttributeSet>("addAttribute", arg0, arg1, arg2);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AttributeContext.html#addAttributes(javax.swing.text.AttributeSet,javax.swing.text.AttributeSet)"/>
            /// </summary>
            /// <param name="arg0"><see cref="Javax.Swing.Text.AttributeSet"/></param>
            /// <param name="arg1"><see cref="Javax.Swing.Text.AttributeSet"/></param>
            /// <returns><see cref="Javax.Swing.Text.AttributeSet"/></returns>
            public Javax.Swing.Text.AttributeSet AddAttributes(Javax.Swing.Text.AttributeSet arg0, Javax.Swing.Text.AttributeSet arg1)
            {
                return IExecute<Javax.Swing.Text.AttributeSet>("addAttributes", arg0, arg1);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AttributeContext.html#removeAttribute(javax.swing.text.AttributeSet,java.lang.Object)"/>
            /// </summary>
            /// <param name="arg0"><see cref="Javax.Swing.Text.AttributeSet"/></param>
            /// <param name="arg1"><see cref="object"/></param>
            /// <returns><see cref="Javax.Swing.Text.AttributeSet"/></returns>
            public Javax.Swing.Text.AttributeSet RemoveAttribute(Javax.Swing.Text.AttributeSet arg0, object arg1)
            {
                return IExecute<Javax.Swing.Text.AttributeSet>("removeAttribute", arg0, arg1);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AttributeContext.html#removeAttributes(javax.swing.text.AttributeSet,java.util.Enumeration)"/>
            /// </summary>
            /// <param name="arg0"><see cref="Javax.Swing.Text.AttributeSet"/></param>
            /// <param name="arg1"><see cref="Java.Util.Enumeration"/></param>
            /// <returns><see cref="Javax.Swing.Text.AttributeSet"/></returns>
            public Javax.Swing.Text.AttributeSet RemoveAttributes(Javax.Swing.Text.AttributeSet arg0, Java.Util.Enumeration<object> arg1)
            {
                return IExecute<Javax.Swing.Text.AttributeSet>("removeAttributes", arg0, arg1);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AttributeContext.html#removeAttributes(javax.swing.text.AttributeSet,javax.swing.text.AttributeSet)"/>
            /// </summary>
            /// <param name="arg0"><see cref="Javax.Swing.Text.AttributeSet"/></param>
            /// <param name="arg1"><see cref="Javax.Swing.Text.AttributeSet"/></param>
            /// <returns><see cref="Javax.Swing.Text.AttributeSet"/></returns>
            public Javax.Swing.Text.AttributeSet RemoveAttributes(Javax.Swing.Text.AttributeSet arg0, Javax.Swing.Text.AttributeSet arg1)
            {
                return IExecute<Javax.Swing.Text.AttributeSet>("removeAttributes", arg0, arg1);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.AttributeContext.html#reclaim(javax.swing.text.AttributeSet)"/>
            /// </summary>
            /// <param name="arg0"><see cref="Javax.Swing.Text.AttributeSet"/></param>
            public void Reclaim(Javax.Swing.Text.AttributeSet arg0)
            {
                IExecuteWithSignature("reclaim", "(Ljavax/swing/text/AttributeSet;)V", arg0);
            }

            #endregion

            #region Nested classes

            #endregion

            // TODO: complete the class
        }
        #endregion

        #region BranchElement
        public partial class BranchElement
        {
            #region Constructors
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.BranchElement.html#%3Cinit%3E(javax.swing.text.AbstractDocument,javax.swing.text.Element,javax.swing.text.AttributeSet)"/>
            /// </summary>
            /// <param name="arg0"><see cref="Javax.Swing.Text.AbstractDocument"/></param>
            /// <param name="arg1"><see cref="Javax.Swing.Text.Element"/></param>
            /// <param name="arg2"><see cref="Javax.Swing.Text.AttributeSet"/></param>
            public BranchElement(Javax.Swing.Text.AbstractDocument arg0, Javax.Swing.Text.Element arg1, Javax.Swing.Text.AttributeSet arg2)
                : base(arg0, arg1, arg2)
            {
            }

            #endregion

            #region Class/Interface conversion operators

            #endregion

            #region Fields

            #endregion

            #region Static methods

            #endregion

            #region Instance methods
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.BranchElement.html#positionToElement(int)"/>
            /// </summary>
            /// <param name="arg0"><see cref="int"/></param>
            /// <returns><see cref="Javax.Swing.Text.Element"/></returns>
            public Javax.Swing.Text.Element PositionToElement(int arg0)
            {
                return IExecuteWithSignature<Javax.Swing.Text.Element>("positionToElement", "(I)Ljavax/swing/text/Element;", arg0);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.BranchElement.html#replace(int,int,javax.swing.text.Element[])"/>
            /// </summary>
            /// <param name="arg0"><see cref="int"/></param>
            /// <param name="arg1"><see cref="int"/></param>
            /// <param name="arg2"><see cref="Javax.Swing.Text.Element"/></param>
            public void Replace(int arg0, int arg1, Javax.Swing.Text.Element[] arg2)
            {
                IExecute("replace", arg0, arg1, arg2);
            }

            #endregion

            #region Nested classes

            #endregion

            // TODO: complete the class
        }
        #endregion

        #region Content
        public partial class Content
        {
            #region Constructors

            #endregion

            #region Class/Interface conversion operators

            #endregion

            #region Fields

            #endregion

            #region Static methods

            #endregion

            #region Instance methods
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.Content.html#length()"/>
            /// </summary>
            /// <returns><see cref="int"/></returns>
            public int Length()
            {
                return IExecuteWithSignature<int>("length", "()I");
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.Content.html#getString(int,int)"/>
            /// </summary>
            /// <param name="arg0"><see cref="int"/></param>
            /// <param name="arg1"><see cref="int"/></param>
            /// <returns><see cref="Java.Lang.String"/></returns>
            /// <exception cref="Javax.Swing.Text.BadLocationException"/>
            public Java.Lang.String GetString(int arg0, int arg1)
            {
                return IExecute<Java.Lang.String>("getString", arg0, arg1);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.Content.html#createPosition(int)"/>
            /// </summary>
            /// <param name="arg0"><see cref="int"/></param>
            /// <returns><see cref="Javax.Swing.Text.Position"/></returns>
            /// <exception cref="Javax.Swing.Text.BadLocationException"/>
            public Javax.Swing.Text.Position CreatePosition(int arg0)
            {
                return IExecuteWithSignature<Javax.Swing.Text.Position>("createPosition", "(I)Ljavax/swing/text/Position;", arg0);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.Content.html#insertString(int,java.lang.String)"/>
            /// </summary>
            /// <param name="arg0"><see cref="int"/></param>
            /// <param name="arg1"><see cref="Java.Lang.String"/></param>
            /// <returns><see cref="Javax.Swing.Undo.UndoableEdit"/></returns>
            /// <exception cref="Javax.Swing.Text.BadLocationException"/>
            public Javax.Swing.Undo.UndoableEdit InsertString(int arg0, Java.Lang.String arg1)
            {
                return IExecute<Javax.Swing.Undo.UndoableEdit>("insertString", arg0, arg1);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.Content.html#remove(int,int)"/>
            /// </summary>
            /// <param name="arg0"><see cref="int"/></param>
            /// <param name="arg1"><see cref="int"/></param>
            /// <returns><see cref="Javax.Swing.Undo.UndoableEdit"/></returns>
            /// <exception cref="Javax.Swing.Text.BadLocationException"/>
            public Javax.Swing.Undo.UndoableEdit Remove(int arg0, int arg1)
            {
                return IExecute<Javax.Swing.Undo.UndoableEdit>("remove", arg0, arg1);
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.Content.html#getChars(int,int,javax.swing.text.Segment)"/>
            /// </summary>
            /// <param name="arg0"><see cref="int"/></param>
            /// <param name="arg1"><see cref="int"/></param>
            /// <param name="arg2"><see cref="Javax.Swing.Text.Segment"/></param>
            /// <exception cref="Javax.Swing.Text.BadLocationException"/>
            public void GetChars(int arg0, int arg1, Javax.Swing.Text.Segment arg2)
            {
                IExecute("getChars", arg0, arg1, arg2);
            }

            #endregion

            #region Nested classes

            #endregion

            // TODO: complete the class
        }
        #endregion

        #region DefaultDocumentEvent
        public partial class DefaultDocumentEvent
        {
            #region Constructors
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.DefaultDocumentEvent.html#%3Cinit%3E(javax.swing.text.AbstractDocument,int,int,javax.swing.event.DocumentEvent.EventType)"/>
            /// </summary>
            /// <param name="arg0"><see cref="Javax.Swing.Text.AbstractDocument"/></param>
            /// <param name="arg1"><see cref="int"/></param>
            /// <param name="arg2"><see cref="int"/></param>
            /// <param name="arg3"><see cref="Javax.Swing.Event.DocumentEvent.EventType"/></param>
            public DefaultDocumentEvent(Javax.Swing.Text.AbstractDocument arg0, int arg1, int arg2, Javax.Swing.Event.DocumentEvent.EventType arg3)
                : base(arg0, arg1, arg2, arg3)
            {
            }

            #endregion

            #region Class/Interface conversion operators
            /// <summary>
            /// Converter from <see cref="Javax.Swing.Text.AbstractDocument.DefaultDocumentEvent"/> to <see cref="Javax.Swing.Event.DocumentEvent"/>
            /// </summary>
            public static implicit operator Javax.Swing.Event.DocumentEvent(Javax.Swing.Text.AbstractDocument.DefaultDocumentEvent t) => t.Cast<Javax.Swing.Event.DocumentEvent>();

            #endregion

            #region Fields

            #endregion

            #region Static methods

            #endregion

            #region Instance methods
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.DefaultDocumentEvent.html#getDocument()"/> 
            /// </summary>
            public Javax.Swing.Text.Document Document
            {
                get { return IExecuteWithSignature<Javax.Swing.Text.Document>("getDocument", "()Ljavax/swing/text/Document;"); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.DefaultDocumentEvent.html#getLength()"/> 
            /// </summary>
            public int Length
            {
                get { return IExecuteWithSignature<int>("getLength", "()I"); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.DefaultDocumentEvent.html#getOffset()"/> 
            /// </summary>
            public int Offset
            {
                get { return IExecuteWithSignature<int>("getOffset", "()I"); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.DefaultDocumentEvent.html#getType()"/> 
            /// </summary>
            public Javax.Swing.Event.DocumentEvent.EventType Type
            {
                get { return IExecuteWithSignature<Javax.Swing.Event.DocumentEvent.EventType>("getType", "()Ljavax/swing/event/DocumentEvent$EventType;"); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.DefaultDocumentEvent.html#getChange(javax.swing.text.Element)"/>
            /// </summary>
            /// <param name="arg0"><see cref="Javax.Swing.Text.Element"/></param>
            /// <returns><see cref="Javax.Swing.Event.DocumentEvent.ElementChange"/></returns>
            public Javax.Swing.Event.DocumentEvent.ElementChange GetChange(Javax.Swing.Text.Element arg0)
            {
                return IExecuteWithSignature<Javax.Swing.Event.DocumentEvent.ElementChange>("getChange", "(Ljavax/swing/text/Element;)Ljavax/swing/event/DocumentEvent$ElementChange;", arg0);
            }

            #endregion

            #region Nested classes

            #endregion

            // TODO: complete the class
        }
        #endregion

        #region ElementEdit
        public partial class ElementEdit
        {
            #region Constructors
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.ElementEdit.html#%3Cinit%3E(javax.swing.text.Element,int,javax.swing.text.Element[],javax.swing.text.Element[])"/>
            /// </summary>
            /// <param name="arg0"><see cref="Javax.Swing.Text.Element"/></param>
            /// <param name="arg1"><see cref="int"/></param>
            /// <param name="arg2"><see cref="Javax.Swing.Text.Element"/></param>
            /// <param name="arg3"><see cref="Javax.Swing.Text.Element"/></param>
            public ElementEdit(Javax.Swing.Text.Element arg0, int arg1, Javax.Swing.Text.Element[] arg2, Javax.Swing.Text.Element[] arg3)
                : base(arg0, arg1, arg2, arg3)
            {
            }

            #endregion

            #region Class/Interface conversion operators

            #endregion

            #region Fields

            #endregion

            #region Static methods

            #endregion

            #region Instance methods
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.ElementEdit.html#getChildrenAdded()"/> 
            /// </summary>
            public Javax.Swing.Text.Element[] ChildrenAdded
            {
                get { return IExecuteWithSignatureArray<Javax.Swing.Text.Element>("getChildrenAdded", "()[Ljavax/swing/text/Element;"); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.ElementEdit.html#getChildrenRemoved()"/> 
            /// </summary>
            public Javax.Swing.Text.Element[] ChildrenRemoved
            {
                get { return IExecuteWithSignatureArray<Javax.Swing.Text.Element>("getChildrenRemoved", "()[Ljavax/swing/text/Element;"); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.ElementEdit.html#getElement()"/> 
            /// </summary>
            public Javax.Swing.Text.Element Element
            {
                get { return IExecuteWithSignature<Javax.Swing.Text.Element>("getElement", "()Ljavax/swing/text/Element;"); }
            }
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.ElementEdit.html#getIndex()"/> 
            /// </summary>
            public int Index
            {
                get { return IExecuteWithSignature<int>("getIndex", "()I"); }
            }

            #endregion

            #region Nested classes

            #endregion

            // TODO: complete the class
        }
        #endregion

        #region LeafElement
        public partial class LeafElement
        {
            #region Constructors
            /// <summary>
            /// <see href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/AbstractDocument.LeafElement.html#%3Cinit%3E(javax.swing.text.AbstractDocument,javax.swing.text.Element,javax.swing.text.AttributeSet,int,int)"/>
            /// </summary>
            /// <param name="arg0"><see cref="Javax.Swing.Text.AbstractDocument"/></param>
            /// <param name="arg1"><see cref="Javax.Swing.Text.Element"/></param>
            /// <param name="arg2"><see cref="Javax.Swing.Text.AttributeSet"/></param>
            /// <param name="arg3"><see cref="int"/></param>
            /// <param name="arg4"><see cref="int"/></param>
            public LeafElement(Javax.Swing.Text.AbstractDocument arg0, Javax.Swing.Text.Element arg1, Javax.Swing.Text.AttributeSet arg2, int arg3, int arg4)
                : base(arg0, arg1, arg2, arg3, arg4)
            {
            }

            #endregion

            #region Class/Interface conversion operators

            #endregion

            #region Fields

            #endregion

            #region Static methods

            #endregion

            #region Instance methods

            #endregion

            #region Nested classes

            #endregion

            // TODO: complete the class
        }
        #endregion

    
        #endregion

        // TODO: complete the class
    }
    #endregion
}