# This is a basic workflow to help you get started with Actions

name: CI_GENERATECLASSES

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      GeneratePR:
        description: 'Generate the PR at the end'
        required: true
        default: false
        type: boolean
        
# This workflow contains one job called "build_documentation"
jobs:
  build_classes:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      # Support longpaths
      - name: Support long paths
        run: git config --system core.longpaths true
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: '1'
          submodules: 'true'

      - name: Prebuild
        run: dotnet build --no-incremental --configuration Release src\net\JNetReflector\JNetReflector.csproj

      - name: Set up Apache Maven Central
        uses: actions/setup-java@v4
        with: # running setup-java again overwrites the settings.xml
          distribution: temurin
          java-version: 11
          cache: 'maven'
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
  
      - name: Create Jars for JNet
        run: mvn "-Djcobridgepath=../../../binReflector/net8.0/JCOBridge.jar" --file ./src/jvm/jnet/pom.xml --no-transfer-progress package
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Clear C# generated files
        run: Remove-Item .\src\net\JNet\Generated\* -Recurse -Force -Exclude README.md

      - name: Clear Java generated files
        run: Remove-Item .\src\jvm\jnet\src\main\java\org\mases\jnet\generated\* -Recurse -Force -Exclude README.md

      - run: dotnet build --no-incremental --configuration Release src\net\JNetReflector\JNetReflector.csproj

      - name: Build classes
        shell: cmd
        run: |
          cd binReflector\net8.0
          MASES.JNetReflector.exe -TraceLevel 0 -DestinationRootPath ..\..\src\ -ConfigurationFile ..\..\src\configuration.json
        env:
          JCOBRIDGE_LicensePath: ${{ secrets.JCOBRIDGE_ONLINE }}

      - name: Try Java compilation
        continue-on-error: true
        run: mvn "-Djcobridgepath=../../../binReflector/net8.0/JCOBridge.jar" --file ./src/jvm/jnet/pom.xml --no-transfer-progress package
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Try C# compilation
        continue-on-error: true
        run: dotnet build --no-incremental --configuration Release /p:Platform="Any CPU" /p:NoWarn="0108%3B1030%3B0618" src\net\JNet.sln
 
      - name: Extract commit SHA
        if: ${{ inputs.GeneratePR == true }}
        run: |
          echo "GITHUB_COMMIT_MESSAGE=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
        shell: bash

      - name: Request a PR to commit changes
        if: ${{ inputs.GeneratePR == true }}
        uses: peter-evans/create-pull-request@v7
        with:
          branch-suffix: short-commit-hash
          add-paths: src/*.*
          commit-message: Update generated classes after commit ${{ env.GITHUB_COMMIT_MESSAGE }}
          title: Changes by GitHub action
          body: |
            Automated changes by GitHub action, fix #216
          reviewers: masesdevelopers
          assignees: masesdevelopers
          labels: java, .NET, enhancement 
